### ISSUE TITLE
Allow any object to match Object

### ISSUE THREAD

**Issue by subhog** [aldeed/meteor-simple-schema#115]
I've got a task to add `simple-schema` to a pretty large application. One of the field in a collection was a large object fetched directly from an external package (payment system). I've marked it as `{type: Object, optional: true, blackbox: true}`. Then I got an error:

    Error: failed validation: someDumbField: must be an object

I've checked and the value passed to `someDumbField` was an object indeed. Then it took me quite a bit digging to figure out that simple-schema also checks the *prototype* of the object.

I'm not convinced this is the right solution – what is the reason behind checking the prototype? Our object was perfectly serializable and just pushing it to db worked well.

*If* checking the prototype is the way to go, the error message should reflect that to avoid confusion like mine. Something like `someDumbField: must be a plain object`.

**Comment by abecks** [comment]
@aldeed this is killing me when trying to use [stampit](https://github.com/stampit-org/stampit). Using composition, I dont have a hard type I can validate against. 

I have stamps that look like:

```
const someType = stampit().methods({ .... });
let something = someType();
// comes out as an Object, but the prototype is not directly Object's prototype.
```

and validators for my templates that look like:

```
Template.something.onCreated(function(){
   new SimpleSchema({
      something: {
         type: Object
      }
   }).validate(this.data);
});
```

As per the Meteor Guide: [http://guide.meteor.com/blaze.html#validate-data-context](http://guide.meteor.com/blaze.html#validate-data-context)

Validation fails if type is set to Object, or a SimpleSchema, and regardless of the blackbox setting. Right now it looks like I literally cannot validate a composed object.

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.

**Comment by abecks** [comment]
This is great news! Thanks aldeed. Have you fully adopted React now? Do you have any plans for AutoForm?

**Comment by kyv** [comment]
This link is broken:
https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200

I imaging I'm not the only one looking to update. where did the changelog go?

**Comment by aldeed** [comment]
Sorry, changelog is on v2 branch (https://github.com/aldeed/meteor-simple-schema/blob/v2/CHANGELOG.md#200), but I recommend using the npm package directly. Also, for collection2, see https://github.com/aldeed/meteor-collection2#important-note-the-version-in-this-repo-is-deprecated
