### ISSUE TITLE
ReferenceError: SimpleSchema is not defined

### ISSUE THREAD

**Issue by Meloncon** [aldeed/meteor-simple-schema#127]
After installing AutoForms, which automatically pulls in this package, I follow the example code in the README. Essentially adding the following to a common code area will result in an error in a brand new Meteor project:

``` javascript
Schema = {};
Schema = new SimpleSchema();
```

The error is:

```
/home/ubuntu/projects/test/.meteor/local/build/programs/server/boot.js:186
 }).run();
    ^
ReferenceError: SimpleSchema is not defined
     at app/test.js:23:14
     at app/test.js:25:3
     at /home/ubuntu/projects/test/.meteor/local/build/programs/server/boot.js:155:10
     at Array.forEach (native)
     at Function._.each._.forEach (/home/ubuntu/.meteor/tools/858c88b520/lib/node_modules/underscore/underscore.js:79:11)
     at /home/ubuntu/projects/test/.meteor/local/build/programs/server/boot.js:82:5

=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

Any suggestions?

**Comment by Metrophobe** [comment]
hi aldeed upgrading old project to new meteor ... and I had simpleschema working (through atmosphere).... now is it correct if I add simpl-schema : "latest" within the package.json dependencies section ...since it is now a node module ?  I am getting a ReferenceError SimpleSchema not defined ..... can I get around this issue without having to install the meteor version?
