### ISSUE TITLE
Allow more than one type

### ISSUE THREAD

**Issue by TimoRuetten** [aldeed/meteor-simple-schema#174]
Is there a recommend way to use more than 1 type for a value ? If not maybe it would be a nice-to-have. 

For example:

In my case I build a easy Category-Tree with simpleSchema. There is the "parent"-property of a document. This property has the key of the parent (a String) or a false (Boolean) if there is no parent for this category. 

A very very simple case but I do not get it if this is still possible to do with SimpleSchema atm.

**Comment by Siyfion** [comment]
@aldeed Is there at least a work around for this in the time being? Or do I have to remove the schema from the collection entirely?

Is there any time-frame for this "any" value to be added?

**Comment by aldeed** [comment]
I can't commit to a timeframe at the moment. You can always modify that property only on the server and disable validation whenever you do it. Or next it within an object that has `blackbox: true`. Or change your schema to eliminate the need.

**Comment by jamgold** [comment]
I am revisiting this and figured out that when I define my Schema on the client I can actually make the type variable like so
```
Schema.Bird = new SimpleSchema({
 plumage: {
  type: String
 }
});
Schema.Mammal = new SimpleSchema({
 legs: {
  type: Number
 }
});
Schema.Pet = new SimpleSchema({
 name: {
  type: String
 },
 type: {
  type: String,
  allowedValues: ['Bird', 'Mammal'],
  defaultValue: Session.get('animalType'),
 },
 animal: {
  type: Schema[ Session.get('animalType') ]
 }
})
```
and when used with AutoForm, the form gets rendered according to the value of _animalType_

The problem is that rendering of AutoForm is not reactive. The template containing the AutoForm needs to be destroyed and re-rendered. When I put the Schema definition into a Tracker.autorun and change the type, the form gets rendered with __both__ sub-schemas, ie. the form would show input fields for plumage __and__ legs.

Is there anyway to detach a schema or refresh AutoForm?

**Comment by 7immy** [comment]
Hey @jamgold, Is your example on the client side only? I gave it a go but the server keeps complaining that "ReferenceError: Session is not defined".

**Comment by 7immy** [comment]
+1

**Comment by savvopoulos** [comment]
+1

**Comment by hems** [comment]
seriously you can't have a "Any" type? I thought Object, blackbox:true would do the trick since everything in javascript extends Object...

<joke>really disappointed... i mean is this NoSQL or some sort of java application ? </joke>

**Comment by rafaelcorreiapoli** [comment]
I need to be able to create a field with multiple data types... Is there a workaround for this? like disabling validation on a specific insert, etc...

**Comment by NitroBAY** [comment]
+1, really surprise that almost 2 year after it still not solved. I'm actually surprised that in a **public** and **used** package of **schema** you just **cannot** set **more than one type**. I'll not have time for PR or anything but this seems very simple to check if (typeof anything === object || typeof anything === string),` Match.OneOf(String, Boolean)` seems simple to implement and reliable for instance.

**Comment by d4nyll** [comment]
@NitroBAY quit your complaining. If you've ever tried to maintain multiple open source libraries whilst still holding a day job, let's see how well you hold up. Learn to appreciate other people's effort and work, people don't work for you.

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.

**Comment by yanickrochon** [comment]
The property `oneOf` is present in the npm package, but not in this one.
