### ISSUE TITLE
Make the `clean` function coerce arrays

### ISSUE THREAD

**Issue by zol** [aldeed/meteor-simple-schema#177]
Hey,

Is there a principalled reason that `clean` doesn't coerce a single value e.g `String` into a field that has a `type` of an array e.g `[String]`.

This would be useful for the case where you've serialized a html form consisting of multiple checkboxes with the same `name`. At the time of serialization, you don't know whether you're going to be populating a single field with that name or an array. I'd be happy to work up a PR for this if itsounds reasonable otherwise I'd love to learn more about the problem space and the issues this could cause.

The use case I'm describing looks something like:

``` html
            <input type="checkbox" name="services" value="strategy" id="strategy">
            <label for="strategy" class="btn-toggle">Strategy</label>

            <input type="checkbox" name="services" value="design" id="design">
            <label for="design" class="btn-toggle">Design</label>
```

``` js
var schema = new SimpleSchema({
  services: { 
    type: [String], 
    allowedValues: ["strategy", "design", "engineering", "consulting"]
  }
});

// serialized doc is either:
{ services: "design" }

// - or - 
{ services: ["design", "consulting"] }

// in the former case, after running clean, I would like to end up with a doc that's coerced to
// something that passes the schema validation, in other words:
{ services: ["design"] }
```

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
