### ISSUE TITLE
Add this.addInvalidKeys in custom functions

### ISSUE THREAD

**Issue by feeloo007** [aldeed/meteor-simple-schema#190]
Hello,

Sorry for my bad english.

I wan't to validate an hierarchical objets' structure.

My JSON object is :

```
{
  virtual_map:
    {
	  A01:
	    {
		  V1: {
            TOM: {
			   01: {
			    information: "..."
			   }
			}
          },
          DMZ: {
            TOMCAT: {
			  0001: {
			    information: "..."
			  }
			}
          }		  
		}
	    ,
	  "@01":
	    {
		  V1: {
            TOM: {
			   01: {
			    information: "..."
			   }
			}
          },
          VILLE: {
            MYSQL: {
			  0001: {
			    information: "..."
			  }
			}
          }		  
		}
	}
}
```

First level keys must be Strings in a limited values list, like [ "A01", "A02" ].
JSON example would not validate "@01" is not part of list. 
Not all values must been defined in JSON. Only "A01" is Ok, only "A02" is Ok.
My real list is all value for regex [A-Z]\d\d.

Second levels keys must be Strings in a limited values list [ "V1", "VILLE", "D1", "DMZ" ]

Third levels keys must be Strings contexualised by second level : "TOM" and 'MYS" for "V1" or "D1", "TOMCAT" and MYSQL for "VILLE" or "DMZ".

My first issue is to validate first level keys.

I think to use custom in schema definition.

But I don't understand how to return error on specific keys.

I use SimpleSchema with Collections2 (this tructure is not suitable for a document in an collection but I have many python codes manipulating this structure, I want only replace local FS loading file by DDP meteor's).

```
var customFunction = function() {
  
  self = this
  
  return function( l_invalid_appcodes ) {
    if ( ! _.isEmpty( l_invalid_appcodes ) ) {
 	  return function( ctx ) {
		ctx.addInvalidKeys(
		  _.map(
		    l_invalid_appcodes
			,
			function( invalid_appcode ) {
			  return {
			    name: self.key + "." + invalid_appcode
				,
				type: "keyNotInSchema"
			  }
			}
		  )
		)
	  }( sc.newContext() )
	} 
  }(
    _.difference(
	  _.keys( self.value )
	  , 
	  [ "A01", "A02" ]
	)
  )

}

SimpleSchema.debug = true
var sc = new SimpleSchema(
  {
    virtual_map:
	  {
	    type: Object
		,
		blackbox: true
		,
		custom: customFunction
	  }
  }
)

var vm = new Mongo.Collection( null )
vm.attachSchema( sc )

vm.insert( { virtual_map: {} } )
vm.insert( { virtual_map: { "A01": {} } } )
vm.insert( {
  virtual_map:
    {
	  A01:
	    {
		  V1: {
            TOM: {
			   02: {
			    information: "..."
			   }
			}
          },
          VILLE: {
            TOMCAT: {
			  01: {
			    information: "..."
			  }
			}
          }		  
		}
	    ,
	  "@01":
	    {
		  V1: {
            TOM: {
			   02: {
			    information: "..."
			   }
			}
          },
          VILLE: {
            TOMCAT: {
			  01: {
			    information: "..."
			  }
			}
          }		  
		}
	}
} )
vm.insert( { virtual_map: { "A02": {} } } )
vm.find().fetch()
```

If virtual_map is not blackbox: true, this.value = {} in custom function.

I could add errors in newContext() but I don't understand if it is possible to transmit this error has result of custom function... Do I need a define a new kind of errors ? But how to get specific errors messages ?

Can you tell me if I am totally wrong ? And if it will be possible to validate sub objects key's ?

Best Regards

Philippe

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.

**Comment by sylido** [comment]
If this doesn't work for someone - just make sure to add a `setTimeout(function() { add invalid keys here }, 100)` that happens after your validation completes - then it shows up just fine.
