### ISSUE TITLE
SimpleSchema.RegEx.Email

### ISSUE THREAD

**Issue by leebenson** [aldeed/meteor-simple-schema#224]
Regex is allowing values through like "lee@whatever" (no TLD)

I've been using the following regex successfully:

    /[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/i

It's not perfect, but it's good for 99.9% of use cases.

**Comment by aldeed** [comment]
The email regex has been debated several times, and in the end I decided to use the expression suggested by W3C.

https://github.com/aldeed/meteor-simple-schema/blob/803bfc9155de6a9fae99eba3df2d5c7a7624097b/simple-schema.js#L542-L545

The problem is that TLD isn't required for it to be a valid address. Most apps probably want TLDs but some won't require them. And the only way to truly validate an email address is to try to send mail to it.

**Comment by vskarine** [comment]
@aldeed in this case you should update README.md because it states following:
SimpleSchema.RegEx.Email for external emails (requires a tld like .com)

**Comment by aldeed** [comment]
Done thanks.

**Comment by williamli** [comment]
i think you can have both
SimpleSchema.RegEx.Email 
and
SimpleSchema.RegEx.EmailWithTLD

:+1:

**Comment by ffflorian** [comment]
I understand. Would you mind an additional schema `SimpleSchema.RegEx.EmailWithTLD`?

Also emails with non-latin characters (cyrillic, greek, chinese, etc.) domains/usernames don't work for now.
