### ISSUE TITLE
Allow label option to be a function

### ISSUE THREAD

**Issue by rclai** [aldeed/meteor-simple-schema#226]
Moved this over from autoform repo.

Sort of like autoValue where you can do this.field('someOtherField'). Example:

```
{
    type: String,
    label: function () {
         if (this.field('someOtherField').value === 'someValue')) {
                return 'My Custom Label';
         }
         return 'My Default Label';
    }
}
```
Further, if this field was within an array or deeply embedded in arrays it would be useful to reference
```
this.field('someArr.$.someField').value
```

Perhaps this could be connected to the reactivity needed in #483.

**Comment by st3phan** [comment]
+1

**Comment by miri-am** [comment]
+1

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
