### ISSUE TITLE
manual Validation vs custom Validation

### ISSUE THREAD

**Issue by gussandy** [aldeed/meteor-simple-schema#235]
Hi All, Could someone please explain to me the difference between MV in AutoForm and CV in SimpleSchema and the if possible the use case(s) for each. Cheers

**Comment by aldeed** [comment]
A custom validation function is in your schema and must pass like all other types of validation every time you validate against that schema.

Manual validation refers to manually adding a validation error to the list of errors for a validation context, which could be any arbitrary error and can be done at any time. This is done primarily to make that error display on the screen along with other errors. It isn't necessarily fully secure because the actual validation process does not know about it.

**Comment by gussandy** [comment]
@aldeed Thxs for your explanation.
