### ISSUE TITLE
`clean` method should not modify original object, but return a new object (?)

### ISSUE THREAD

**Issue by victorbstan** [aldeed/meteor-simple-schema#250]
Hi, 

I'm wondering if its possible to reconsider the decision that the original object should be modified by clean (or any other method) instead of returning a new cleaned object and leaving the old one as is?

Consider many arguments against 'mutable' objects and embracing 'immutability'... 

http://programmers.stackexchange.com/questions/151733/if-immutable-objects-are-good-why-do-people-keep-creating-mutable-objects

https://github.com/facebook/immutable-js

ETC.

And perhaps a feature request if deemed appropriate, to either have `clean` method take a flag to leave original object as is and return the modified one, if overhauling the original behaviour is too risky.

**Comment by aldeed** [comment]
In the beginning it returned a new object, but collection2 does cleaning within `deny` functions and currently the only way to do that is to clean the object in place, so that's why it was changed. I believe the cleaning also became faster as a result of the change.

I have suggested a few times to MDG that there should be a better way of hooking into inserts and updates coming from untrusted code on the server, but it doesn't seem like a priority for them.

I didn't see the mutation as an issue since anyone not wanting the original object to change can clone it prior to cleaning. Probably would have to deep clone. That said, I'm far from an expert on the immutability debate.

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
