### ISSUE TITLE
Breaking on optional-but-non-null field

### ISSUE THREAD

**Issue by hujhax** [aldeed/meteor-simple-schema#255]
Say I have a field "foo."  It's an optional field, but if you set it to some value, that value cannot be null.  So: you can leave "foo" out completely, or you can set it to something non-null.  Those are your options.

So in my schema, I set "optional: true" on foo.  Then I set up a custom validator for foo that returns "CannotSetToNull" or something if someone's trying to assign "null" to foo.

With me so far?

Now let's say I pass in an object that does *not* set foo to anything.

What I expect: SimpleSchema notices "optional: true", notices the field is missing, never runs the custom validator, and the field checks out.

What happens: SimpleSchema runs the custom validator, tells it we're trying to set foo to null, and we get a CannotSetToNull error.

Is this intended behavior?

**Comment by aldeed** [comment]
Yes it's intended because there are cases where people need custom validation based on the *absence* of a field. You can check `this.isSet` in the validator, but I can't actually remember whether that returns `true` or `false` for `null`. Hopefully `true`. SS is based on mongo, and mongo treats `null` and missing the same in 99% of cases.

**Comment by hujhax** [comment]
Perfect answer -- thanks!
