### ISSUE TITLE
Adding keys to schema after initial definition

### ISSUE THREAD

**Issue by copleykj** [aldeed/meteor-simple-schema#257]
I was wondering if it's possible to add keys to a schema after it's already defined.. Currently I'm working on a package where I define a schema but want the package to be slightly extensible and therefore the schema might need to be added to after it's initial inception.. It looks as though I can add directly to the schemaInstance._schema and that would work but it would be nice to not bypass the initial checks that are run in the constructor.

**Comment by aldeed** [comment]
If the schemas are attached to collections using collection2, then package users can simply attach their extension schema after that, and the two schemas will be merged.

If you're using the schema for something else, then you'd have to replicate that same feature the way collection2 package does it. There isn't currently a simple, safe way to alter a schema object after creation.

Otherwise you could do it the way telescope does it, creating and attaching the schema after allowing startup code to extend it: https://github.com/TelescopeJS/Telescope/blob/4d40664d0819a25c9f8646085f326999fdcc0705/collections/posts.js#L6-L204

**Comment by copleykj** [comment]
Oh, very nice.. I didn't realize that Collection2 would merge schemas, exactly what I need then.. Thanks so much!
