### ISSUE TITLE
Object.whateverId label is inferred incorrectly as "Whatever" instead of "Whatever id"

### ISSUE THREAD

**Issue by lovetostrike** [aldeed/meteor-simple-schema#260]
Before I send a PR to fix this, just want to make sure if this is side-effect of this code:
```
humanize: function() { //modified from underscore.string
      if (this.s === null || this.s === undefined)
        return new S('')
      var s = this.underscore().replace(/_id$/,'').replace(/_/g, ' ').trim().capitalize()
      return new S(s)
    }
```
Is there any reason to explicily remove "_id"?

**Comment by aldeed** [comment]
In a lot of cases this is what you want because if you're storing an ID reference to another collection, then you're probably labeling it as `User` rather than `User ID` in the interface. But I agree this may not be the best place for that decision to be made, so a PR to remove that is fine.

**Comment by mhwheeler** [comment]
"Humanize" can cause ambiguous error messages in validation if two keys humanize into the same string. An example is: `{externalSource: 'google', externalSourceId: '123googleid456'}`. If the schema requires both these keys and you insert a doc with `externalSource` but not `externalSourceId` the error message would be: "External source is required".

@lovetostrike were you going to propose a change?

**Comment by lovetostrike** [comment]
@mhwheeler I added a PR as you can see above, but it failed the CI and I haven't got a chance to get back to it.

**Comment by aldeed** [comment]
@marcodejongh, does your new humanize stuff fix this? Can you add a test for this? Otherwise I will when I have time.

**Comment by marcodejongh** [comment]
@aldeed It does fix it but only because the package author made a mistake https://github.com/jxson/string-humanize. The package should be stringjs humanize behaviour but in a isolated package, I guess the author forgot to add the removing of id postfixes.

I've added tests for this in #499 the only case that will still cause confusion now is if you have:

```
externalSourceId: 123
externalSource_id: 456
```

Which will both translate to ```External source id``` but in that case it's the schema design that needs to be fixed not the simple schema code.
