### ISSUE TITLE
Support (or advice) for JSON schema

### ISSUE THREAD

**Issue by wmodes** [aldeed/meteor-simple-schema#269]
I currently have validated nested JSON schema. I know simple-schema doesn't support JSON schema, but I wonder if you've given it thought?  Consider it a feature request -- you are already so close.

Any advice on converting JSON schema to simple schema?  My fantasy is that you'll say, "Oh use the --something option to use json-schema," or "use the conversion script in the repo."

**Comment by aldeed** [comment]
It has been suggested before but there is currently no support. I would like to explore it eventually, but until I have time, I'd say it's a good opportunity for someone else to make a wrapper package. When I looked into it before, there were enough differences in the small details that it added up to a rather large project.

**Comment by wmodes** [comment]
I wouldn't expect it to be easy. But perhaps that is an opportunity for you to use up all that extra free time I'm sure you probably have. :-)

**Comment by fullflavedave** [comment]
@wmodes:  I'm going to try to create a JSONSchema smart package that integrates with Collection2/SimpleSchema.  If you send me some samples of the JSON Schema you have, I can make an attempt to make it work for your cases.  I also would welcome any help with the package since I'm pretty new to JavaScript.

**Comment by bshamblen** [comment]
@fullflavedave Have you made any progress on creating a JSON schema package that works with simple schema? I looked at your public repositories but didn't see anything obvious. If you haven't I'll start working on one.

**Comment by fullflavedave** [comment]
@bshamblen:  I started on a local package but only completed enough for a quick prototype for my team's needs before priorities changed.  I'm not sure any of it will be useful to you, but I'll check into github what I have so far.  I need to get back to this in a couple of weeks, so any contributions are very appreciated.  My initial thoughts that I vetted with @aldeed were:

- Create a JSONSchema package and include a `JSONSchema.prototype.toSimpleSchema()` method for using the existing collection2 package as is.
- Add a `Mongo.Collection.prototype.attachJSONSchema(new JSONSchema())` method to the collection2 package.  This new method would just call `JSONSchema.toSimpleSchema()` and call the existing `Mongo.Collection.attachSchema()` method in collection2.

And @aldeed responded with this:
I had in mind `JSONSchema.toSimpleSchema()`, but there’s no reason you couldn’t add the `attachJSONSchema` prototype function, too, I guess.

I’m interested to see how it goes. I can mention it in the readme if you get it working. Since some of the SS features don’t relate to JSONSchema (custom, autoValue, etc.) there may need to be an easy way to provide some extended options that will be added to the converted schema.

**Comment by bshamblen** [comment]
@fullflavedave Thanks getting the ball rolling. Please let me know when you've made your project public and I'll take a look at it.

**Comment by fullflavedave** [comment]
@bshamblen Here is my very basic start for a package so far:  https://github.com/fullflavedave/meteor-json-schema

As you can see, the transformation from JSONSchema to SimpleSchema is pretty lame (just take everything from `properties`), but this is mainly due to my total lack of knowledge of JSONSchema.  Just a proof of concept for me.

A working test/example is in json-schema-tests.js.

**Comment by fullflavedave** [comment]
@bshamblen How is this effort going?  I’m about to dive back into generating forms/pages from backend-produced JSON, and I wanted to check in with you before I did anything.

Thanks,
Dave

**Comment by bshamblen** [comment]
@fullflavedave In the interest of getting it done as quickly as possibly I basically started from scratch, and published the [package](https://atmospherejs.com/bshamblen/json-simple-schema) to Atmosphere a few weeks ago. 

It currently supports most of the basic validation options that map to SimpleSchema's built in validation. It doesn't support a `definitions` block with multiple schemas or `$ref`s to internal/external schemas, but the basic functionality is there for a single schema. 

Ideally it would parse any JSON schema document and return a dictionary of schemas (one for each definition item), but I didn't have time to get it done before I had to move on to the next task.

My main use for this was to take a JSON schema document, which is generated by our API server, to automatically generate a form (using Autoform), and post the data to our API server in the Autoform `onSubmit` hook.

**Comment by fullflavedave** [comment]
@bshamblen That's great -- I'll take a look and hopefully use it.

**Comment by bpartridge** [comment]
Amazing stuff @bshamblen! 

To anyone else watching this thread, I just sent a pull request adding support for internal JSON refs: https://github.com/Yodata/meteor-json-simple-schema/pull/1

My company will be using this feature in production - many thanks to all who have contributed to let us get from the JSON schemas we use internally to full autoforms-powered GUI!

**Comment by SachaG** [comment]
What about doing the opposite transformation - from SimpleSchema to JSON-Schema? Has anybody worked on this by any chance?

**Comment by zeroasterisk** [comment]
I was just asking for this... SimpleSchema --> JsonSchema and then the npm world of JSON schema becomes available to us, like this https://github.com/json-schema-faker/json-schema-faker
