### ISSUE TITLE
Logging of validation messages

### ISSUE THREAD

**Issue by marcodejongh** [aldeed/meteor-simple-schema#270]
My product owner wants to log all the form validation errors.  Which we handle all with the use of simple schema. 
Now I could write my own wrapper around simpleshema and have the wrapper do the logging. 

But I think this might be something nice to build into simple schema because I feel more people would want this functionality. What do you think @aldeed ? 

Would that be something you'd be willing to merge into master?
In your opinion what would be the best place to write to the db? ```messageForError``` to me looks like the ideal place because you'd want a log entry for every separate error message.

**Comment by aldeed** [comment]
I think the main hurdle is that many of the functions are reactive on the client (or the functions that call them are), so you'd potentially end up logging several times for what is essentially just one error. To avoid db bloat, a smarter implementation might be necessary.

It might work to pass an option to `validate` function, having it log any errors before returning. There are still situations when it can be called many times for the same error, but some sort of throttling + duplicate checking logic could guard against that.

It might be complex enough to warrant being an add-on package instead of included in core, but we can add a generic hook in core to make it easier to "plug in".
