### ISSUE TITLE
clean method on context

### ISSUE THREAD

**Issue by smeijer** [aldeed/meteor-simple-schema#273]
There should be a clean method on a (named) context. So we could do something like:

```javascript
Template.foo.created = function() {
  var instance = this;
  instance.schema = LoginSchema.namedContext('loginForm');
}

Template.foo.events({
  'submit .form': function(event, instance) {
    var doc = { user: 'user', password: 'bar' };
    var schema = instance.schema;
    
    schema.clean(doc); // instead of LoginSchema.clean(doc)
    var isValid = schema.validate(doc);
  }
});
```

**Comment by aldeed** [comment]
Yeah, I suppose that could be handy.

**Comment by ChenRoth** [comment]
alternatively, you can use:

```
var context = aSchema.namedContext('foo');
context._simpleSchema.clean(obj);
```

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
