### ISSUE TITLE
[FR] `this` in  min/max/allowedValues functions

### ISSUE THREAD

**Issue by serkandurusoy** [aldeed/meteor-simple-schema#276]
Being able to evaluate functions for min/max/allowedValues is great, but it would be just plain awesome if we had a `this` context in those functions as well, just like we have in custom and autoValue.

**Comment by farald** [comment]
This would definitively be a big + for complex usability.

**Comment by eoliphan** [comment]
+1 for this as well

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
