### ISSUE TITLE
Add a mySimpleSchema.addDocValidator(function) 

### ISSUE THREAD

**Issue by skeetmtp** [aldeed/meteor-simple-schema#281]
Similar to mySimpleSchema.addValidator() but at the document level, so we can easily do validation over the entire document.

**Comment by pcorey** [comment]
+1

As far as I can tell, using this.value('somekey').value in an addValidator or custom function won't have access to that value if somekey wasn't being set or updated in the transaction.

For example, if I'm updating 'someotherkey', but I want to validate it against 'somekey', I couldn't do that.

    MySchema.simpleSchema().addValidator(function() {
        var somekey = this.value('somekey').value; //Undefined... :(
        var someotherkey = this.value('someotherkey').value;
        if (somekey === someotherkey) {
            return 'lol_error';
        }
    }

And then later...

    MySchema.update({_id: ...}, {
        someotherkey: '1337'
    });

There really isn't a good way of doing non-trivial validation that spans multiple fields right now.

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
