### ISSUE TITLE
Should pick() everything under array or object when picking array or object

### ISSUE THREAD

**Issue by Hellyna** [aldeed/meteor-simple-schema#284]
Howdy,

As mentioned in the title, to reproduce the issue, simply create a brand new Meteor project, remove all files cept `.meteor`, remove `autopublish` and `insecure`, add `aldeed:simple-schema`. Then add a single js file naming it whatever you want with the following contents:

```javascript
MainSchema = new SimpleSchema({
  stringArray: {
    type: [String]
  }
});

DerivedSchema = MainSchema.pick('stringArray');
```

Try to run `meteor` in that directory and see it errors:

```
W20150307-22:42:49.991(8)? (STDERR)           
W20150307-22:42:49.993(8)? (STDERR) /home/hellyna/.local/lib/meteor/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150307-22:42:49.993(8)? (STDERR) 						throw(ex);
W20150307-22:42:49.993(8)? (STDERR) 						      ^
W20150307-22:42:50.046(8)? (STDERR) Error: Invalid definition for stringArray.$ field.
W20150307-22:42:50.046(8)? (STDERR)     at packages/aldeed:simple-schema/simple-schema.js:465:1
W20150307-22:42:50.046(8)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150307-22:42:50.046(8)? (STDERR)     at [object Object].SimpleSchema (packages/aldeed:simple-schema/simple-schema.js:462:1)
W20150307-22:42:50.046(8)? (STDERR)     at [object Object].SimpleSchema.pick (packages/aldeed:simple-schema/simple-schema.js:657:1)
W20150307-22:42:50.046(8)? (STDERR)     at app/bug.js:7:28
W20150307-22:42:50.046(8)? (STDERR)     at app/bug.js:10:3
W20150307-22:42:50.046(8)? (STDERR)     at /home/hellyna/someproj/.meteor/local/build/programs/server/boot.js:205:10
W20150307-22:42:50.047(8)? (STDERR)     at Array.forEach (native)
W20150307-22:42:50.047(8)? (STDERR)     at Function._.each._.forEach (/home/hellyna/.local/lib/meteor/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150307-22:42:50.047(8)? (STDERR)     at /home/hellyna/someproj/.meteor/local/build/programs/server/boot.js:116:5
```

**Comment by aldeed** [comment]
You need to pick the array item field, too. We could possibly have it do this automatically to prevent confusion.

```js
MainSchema.pick('stringArray', 'stringArray.$');
```

**Comment by delgermurun** [comment]
Please at least document it, in the meantime.

**Comment by fabyeah** [comment]
+1 needs documentation if it isn't done automatically.

**Comment by paulbalomiri** [comment]
Also, when picking the list content schema `list.$` there is a silent bug:

````
s=new SimpleSchema
 l: {type:Array}
s2= s.pick('l.$')

```
`s2.schema().l.type` is now `Object()` instead of `Array()`

**Comment by Pagebakers** [comment]
Having issues with this aswel, in combination with AutoForm

```javascript
var subSchema = new SimpleSchema({
  field1: {
   type: String
  },
  field2: {
   type: String
  }
});
var schema = new SimpleSchema({
  field: {
    type: [subSchema]
  }
});

var pickedSchema = schema.pick('field', 'field.$', 'field.$.field1', 'field.$.field2');
```

```handlebars
{{> quickForm schema=pickedSchema}}
```

Now it creates an afArrayField for 'field', afObjectField for 'field.$' and afQuickFields for 'field2' and 'field2'

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and should fix this bug.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
