### ISSUE TITLE
_globalMessages.regEx array overwritten when calling SimpleSchema.messages()

### ISSUE THREAD

**Issue by wagerfield** [aldeed/meteor-simple-schema#287]
I love your validation messaging system, but am having problems extending the regEx array because of the implementation of the [messages](https://github.com/aldeed/meteor-simple-schema/blob/master/simple-schema.js#L921) method.

When passing an object to `SimpleSchema.messages()` with a `regEx` array set on it, the original regEx array is replaced with the new one. I would like to extend this instead. To circumvent this, I am currently doing the following:

```
SimpleSchema.RegEx.Word = /^[a-zA-Z-]{2,25}$/;

SimpleSchema._globalMessages.regEx.push({
  exp: SimpleSchema.RegEx.Word,
  msg: '[label] must be a valid word'
});
```

..however, this bypasses the reactive update and feels a little dirty.

Lodash offers a [merge](https://lodash.com/docs#merge) function to allow deep extension of objects, but underscore does not unfortunately. Is there a more elegant solution to the one above, or could an additional method or parameter be added to the current implementation to allow for deep extension / merging of custom regEx messages?

Many Thanks

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and should fix this bug.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
