### ISSUE TITLE
Add modifyValue

### ISSUE THREAD

**Issue by wagerfield** [aldeed/meteor-simple-schema#292]
I would like to use `autoValue` to format array items, but am getting the error:

`An array item field (one that ends with ".$") cannot have autoValue.`

My use case is converting an array of tags to lowercase:

```
var ss = new SimpleSchema({
    'tags': {
        type: [String],
        optional: true,
        minCount: 1,
        maxCount: 5
    },
    'tags.$': {
        type: String,
        regEx: /^[a-z-]{2,25}$/,
        autoValue: function() {
            if (this.isSet) {
                return this.value.toLowerCase();
            }
        }
    }
});
```

What is the reason for not allowing array items to respect the `autoValue` function?

**Comment by aldeed** [comment]
I think the main reason is because autoValue can automatically generate a value upon cleaning, so if that's the case, how many do you want to generate? There is no way for simple-schema to know how many array items you want.

In your case, you want it to run only for array items that are set, so it does make sense. It might be possible to refine the logic so that we do run it for array items, but we clarify that it runs only if the value is already present, allowing you to change it.

**Comment by wagerfield** [comment]
Makes perfect sense and personally I think that would offer an additional layer of use to the autoValue function. As you said (and what I had assumed to be the case), the autoValue function would only run if a) the array had been set and b) there were items within it.

Let me know if you'd like me to take a look at this :smiley:

**Comment by serkandurusoy** [comment]
I have exactly the same use case. I'm accepting ad-hoc tags into an array and want tags to be all lowercase.

@wagerfield how did you solve this one in your case?

**Comment by aldeed** [comment]
My plan to fix this is to add a `modifyValue`, which will be allowed for array items and will run only if there is a value being set.

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
