### ISSUE TITLE
Insufficient validation and cleaning of objects in arrays and of null values

### ISSUE THREAD

**Issue by mologie** [aldeed/meteor-simple-schema#314]
I stumbled across this because of the recent AutoForm bug where null entries are left in arrays:

Test case:
```js
var arraySchema = new SimpleSchema({
    names: { type: [String] },
    testField: { type: String, optional: true }
});
var validObject = { names: ["String"] };
var validEmptyObject = { names: [] };
var invalidObject = { names: [{hello:"world"}] };
var certainlyInvalidObject = { zebra:"striped" };
var evilObject = { names: [null] };
var cleanMe = { names: [], testField: null };
var validationContext = arraySchema.newContext();
console.log("validObject valid?", validationContext.validate(validObject));
console.log("validEmptyObject valid?", validationContext.validate(validEmptyObject));
console.log("invalidObject valid?", validationContext.validate(invalidObject));
console.log("certainlyInvalidObject valid?", validationContext.validate(certainlyInvalidObject));
console.log("evilObject valid?", validationContext.validate(evilObject));
console.log("cleanMe valid?", validationContext.validate(cleanMe));
arraySchema.clean(validObject);
arraySchema.clean(validEmptyObject);
arraySchema.clean(invalidObject);
arraySchema.clean(certainlyInvalidObject);
arraySchema.clean(evilObject);
arraySchema.clean(cleanMe);
console.log("validObject:", JSON.stringify(validObject));
console.log("validEmptyObject:", JSON.stringify(validEmptyObject));
console.log("invalidObject:", JSON.stringify(invalidObject));
console.log("certainlyInvalidObject:", JSON.stringify(certainlyInvalidObject));
console.log("evilObject:", JSON.stringify(evilObject));
console.log("cleanMe:", JSON.stringify(cleanMe));
```

Expected output:
```txt
validObject valid? true
validEmptyObject valid? true
invalidObject valid? false
evilObject valid? false
cleanMe valid? false
validObject: {"names":["String"]}
validEmptyObject: {"names":[]}
invalidObject: {"names":[]}
certainlyInvalidObject: {}
evilObject: {"names":[]}
cleanMe: {"names":[]}
```

Actual output:
```txt
validObject valid? true                 | OK
validEmptyObject valid? true            | OK
invalidObject valid? false              | OK
certainlyInvalidObject valid? false     | OK
evilObject valid? true                  | error
cleanMe valid? true                     | error
validObject: {"names":["String"]}       | OK
validEmptyObject: {"names":[]}          | OK
invalidObject: {"names":[{}]}           | error
certainlyInvalidObject: {}              | OK
evilObject: {"names":[null]}            | error
cleanMe: {"names":[],"testField":null}  | error
```

**Comment by aldeed** [comment]
Let's take these one by one:

1. `evilObject` should not be valid. I agree. Maybe bug.
2. `cleanMe` should not be valid. I disagree. `testField` is optional and there are no minimum number of array items required.
3. `invalidObject` should be `[]` instead of `[{}]` after cleaning. Maybe.
4. `null` should be removed from `evilObject` array. I'm not really sure whether there might be valid use cases for having `null` array items, and since you can't set an array item schema as `optional`, there's really no way to know whether cleaning should remove them or not. Maybe it could be a new option on the clean function (`leaveNullsInArrays: true`).
5. `testField: null` should not be in `cleanMe` after cleaning it. I agree, but this seems like a pretty basic cleaning which I thought we had tests for, so I'm surprised it was not cleaned.

I can add tests for any of these that don't already have them, and then fix as appropriate.

**Comment by mologie** [comment]
The concern that I have with `null` and `{}` objects is that they are valid Mongo types. SimpleSchema is used a lot for sanitizing database input, and I think that allowing any other type but the type specified in the schema to pass is a recipe for trouble. Let me explain my reasoning for some of the cases:

* 2. `cleanMe` should be invalid because `testField` is defined but its type is not `String`
* 3. `invalidObject` should be invalid and cleaned to `{names:[]}` because `{}` is not a string. (I would expect to be able to iterate over the cleaned array and safely use string methods on each member, such as `match`.)
* 4. As above, `null` is not a string

Cheers, Oliver

**Comment by aldeed** [comment]
SS treats `null` and `undefined` the same. Either are OK if `optional: true`. It does this because that's what Mongo does in most cases.

For 4, I agree removing nulls makes sense as the default, but I don't want to do it without adding the `leaveNullsInArrays` option because I guarantee there are many others who do want `nulls` mixed in with strings.

**Comment by iliasch** [comment]
I found a problem which seems to be related:

var mySchema = {
  something: { type: [Object] }
}

var myData = [{ field1: value1, field2: value2}];

console.log(mySchema.clean(myData));
> [ { } ]

(The data is removed even though it's a valid object)

**Comment by mologie** [comment]
I think you are required to set `blackbox: true` in your field if you do not wish SimpleSchema to clean unknown fields. Else, you have to register individual fields like in `Schema.User` [here](https://github.com/aldeed/meteor-collection2#attach-a-schema-to-meteorusers).

**Comment by iliasch** [comment]
By registering the individual fields solves the problem, but what if I do not know the contents of the objects? Shouldn't [Object] accept every possible array of objects?

**Comment by boldkhuu** [comment]
Null needs to be cleaned. @aldeed When will be this issue resolved?

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and should fix this bug.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
