### ISSUE TITLE
Ineffectively evaluating other schema functions when only needing label

### ISSUE THREAD

**Issue by dalgard** [aldeed/meteor-simple-schema#320]
I was wondering why my `min` function got evaluated twice. I think only the label should be requested in [this line](https://github.com/aldeed/meteor-simple-schema/blob/a6e0dc8ccd5ef430ef94aa3cb6f8851cccc6dd72/simple-schema.js#L884), since it's the only property used – like this:

```javascript
var def = self.getDefinition(key, "label");
```

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and should fix this bug.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
