### ISSUE TITLE
Feature request: Helper Only Fields

### ISSUE THREAD

**Issue by boustanihani** [aldeed/meteor-simple-schema#331]
I assume this is not yet an out-of-the-box feature, so consider this as a feature request :)

How about making it possible to declare **helper fields**, that **do not get persisted to the database** but may be used inside templates when a schema is attached to a collection (example: ```fullName``` as a shortcut for ```firstName + ' ' + lastName```) and may also be used inside **autoforms** for reactive data visualizations or maybe inside custom functions for more complex validations...

IMO, adding what ```dburles:collection-helpers``` currently offers to simpleschema, collection2 & autoform and extending the functionality to also allow nesting helpers (Check: https://github.com/dburles/meteor-collection-helpers/issues/34) would be great from an organizational point of view. **By this, one could combine all data-related fields (persistent & non-persistent) into one single unit**.

**Comment by dsummersl** [comment]
+1

**Comment by serkandurusoy** [comment]
Ah, I was just about to post a feature request, naming them "transient" fields.

My use case is the following (with AutoForm):

I have an address form which allows the user to select the city, and then the province (among the provinces that happen to be in that city) so I basically have a parent>child dependent select.

In order to let the user first select a city, both city and province should be on the schema. But then, that means the city will also be persisted, which I don't want. It is an unnecessary denormalization.

It would be great if I were able to mark the field as `transient: true` right in the schema definition, regardless of the presence of autoform.

I worked around it by unsetting it:

```javascript
city: {
  optional:true,
  autoValue: function() {
    this.unset();
  }
}
```

Now it appears on the form, I can interdepend it with other fields, but get rid of it once it does its job.

Still a hack, though.

**Comment by aldeed** [comment]
Collection2 used to have virtual fields but I removed since collection-helpers was created and does a find job. As far as needing fields on autoform, this is usually done by providing a form schema that is different from the collection schema and then adjusting the form document before saving.
