### ISSUE TITLE
Confusing custom error message scenario

### ISSUE THREAD

**Issue by sylido** [aldeed/meteor-simple-schema#332]
If we have this complex type schema where `profile` has it's own schema:
```
Schema.User = new SimpleSchema({
  profile: {
      type: Schema.UserProfile,
      optional: true
    }
})

Schema.UserProfile = new SimpleSchema({
    firstName: {
      type: String,
      regEx: /^[a-zA-Z-]{2,25}$/,
      optional: true
    },
    lastName: {
      type: String,
      regEx: /^[a-zA-Z]{2,25}$/,
      optional: true
    }
})
```

The definition of custom error messages for a specific field doesn't work as described in the documentation - `regex firstName` is what I expected to override the message for that field, but only after tinkering around by chance I found out it's:
```
SimpleSchema.messages({
  "regEx profile.firstName": [
    { msg: "Your First Name should be between 2 and 25 alphabetic characters, hyphens are also allowed." }
  ]
});
```
Could we make a note in the documenation or change the behavior ?
Even when trying to do Schema.UserProfile.messages({...}); the documented behavior still doesn't yield the correct result.

**Comment by aldeed** [comment]
That's because schemas are merged rather than evaluated separately. The plan is to change that eventually, but it's a pretty big project.

We can update the docs.

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
