### ISSUE TITLE
Time type

### ISSUE THREAD

**Issue by Akash-dvd** [aldeed/meteor-simple-schema#345]
Please provide the support for time datatype.

**Comment by aldeed** [comment]
I'm not sure what you mean. JavaScript doesn't have a time datatype. You could store it as hour, minute, second properties with Number type.

**Comment by thomasvanlankveld** [comment]
The html input type [time](http://www.w3schools.com/htmL/html_form_input_types.asp) returns a string; anything between  `00:00` and `23:59`. I'm using this in a form to specify duration.

```html
<input type="time">
```

The simple schema documentation mentions constructor functions can be used for validation; Would it be a good idea for me to write a `Time` constructor? How does a constructor validate?

**Comment by aldeed** [comment]
Yeah, I think string with regex makes the most sense, or parse it before storing and store as minutes since midnight.

For constructor types, it simply validates using `instanceof`. It assumes that your constructor function would do any additional validation needed. You could do a custom `Time` and register it as an EJSON type so that it remains a `Time` object when going over the wire, in/out of database, etc.
