### ISSUE TITLE
trim: false does not work

### ISSUE THREAD

**Issue by joegoldbeck** [aldeed/meteor-simple-schema#348]
I'm getting some weird saving behavior when a string starts or ends with whitespace, even when `trim: false` is set, where SimpleSchema converts a string to a string and trims off whitespace. I'm also getting some weird behavior where some strings are getting oddly mutated upon save. I do not know if these issues are related but it seems possible.

Log:
```
SimpleSchema.clean: autoconverted value <a href='javascript:void(0);' data-context-id='15'>In 1976</a>, Ebola first emerged in Sudan and Zaire, two countries in <a href='javascript:void(0);' data-context-id='15'>Central Africa</a>. This outbreak killed approximately 300 people, and although epidemiologists studied the area extensively, Ebola’s natural reservoir in the environment was never discovered. In 1989, Ebola was also discovered in the Philippines, after monkeys infected with the disease were exported from there to an animal testing laboratory in Reston, Virginia in the United States.  
from string to string for draftStory.verticalSections.$.content
```

Relevant part of my schema:
```
  'content': {
    type: String,
    trim: false
  },
```
https://github.com/readFOLD/FOLD/blob/9b983fd3c92cb17644bba5aad5817a64d78f996c/collections/collections.js#L1219
+
https://github.com/readFOLD/FOLD/blob/9b983fd3c92cb17644bba5aad5817a64d78f996c/collections/collections.js#L1257

Object is inserted here: https://github.com/readFOLD/FOLD/blob/9b983fd3c92cb17644bba5aad5817a64d78f996c/server/fixtures.js#L76 It's pretty vanilla but does end with a space, which is trimmed.

**Comment by kaurinz** [comment]
I experienced the same issue with my project just today.  

It appears that when autoConvert(ion) happens it does not honor the trim setting for a key.

As a temporary workaround I passed {autoConvert:false} in my call to collection.update

**Comment by joegoldbeck** [comment]
@kaurinz Good call! `{autoConvert:false}` is a very fine workaround

**Comment by sroze** [comment]
:+1: , experiencing the same issue !

**Comment by marbemac** [comment]
+1 same issue

**Comment by Siyfion** [comment]
I'm experiencing something very similar to this. I have a schema with field that is set to `trim: false` being referenced in another schema and it simply ignores the `trim` flag and does it regardless! :unamused:

**Comment by eastes** [comment]
{autoConvert:false} worked for me. Except it breaks numbers. Now numbers break the schema. I'll need to find another work around

**Comment by Siyfion** [comment]
@aldeed What is going on with this exactly? I can see that you've made a commit that states that it fixes `trim: false` but, it was on the `devel` branch, in a `lib/clean.js`, which doesn't seem to exist in master as-yet. What's the ETA on getting this fix into a released version? It's causing me so many problems now.

**Comment by nmaro** [comment]
+1

**Comment by nmaro** [comment]
Found a workaround: 

				Collection.update(id,  {/*your update*/}, {
					removeEmptyStrings: false,
					trimStrings: false
				});

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and should fix this bug.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.

**Comment by keyscores** [comment]
+1  @aldeed can you give us an update on the v2 release?
