### ISSUE TITLE
Unexpected validate behavior with classes

### ISSUE THREAD

**Issue by cmnjcs** [aldeed/meteor-simple-schema#362]
Short version: validating an object created from a function unexpectedly indicates a valid object, but insertion into collection fails as expected. If I take the object and deep clone it, and attempt to validate that, SimpleSchema correctly indicates an error.

Any pointers?

Sample code below.

```javascript
    Test = function(a, b) {
      this.a = a;
      this.b = b;
      return;
    }

    TestCollection = new Mongo.Collection('Test');

    TestSchema = new SimpleSchema({
      a: {
        type: Number,
        min: 10
      },
      b: {
        type: Number,
        max: 10
      }
    });

    TestCollection.attachSchema(TestSchema);

    var z = new Test(1,2);

    testContext = TestSchema.namedContext('testing');
    testContext.validate(z);  // returns true
    testContext.isValid();  // returns true

    TestCollection.insert(z);
    // insert failed: Error: A must be at least 10

    var z_obj = JSON.parse(JSON.stringify(z));
    testContext.validate(z_obj);  // returns false
    testContext.isValid();  // returns false
    testContext.invalidKeys();
    // returns [{ name: "a", type: "minNumber", value: 1 }]
```

**Comment by aldeed** [comment]
It intentionally only validates until it hits an object with some non-Object prototype. It assumes that if it's a `Test` object, you will handle validation internally within that object. I guess there could be some way of registering certain types to be fully validated if there is a use case for it.

**Comment by nscarcella** [comment]
+1

I would like to be able to validate a class instance using the schema. Most of the time the schema contains the information to check for my wrappers integrity and re-write that code (or deep clone the object) feels a bit like a stretch.

Plus, having the schema accept objects that the collection rejects sounds kind of inconsistent.

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
