### ISSUE TITLE
Can't set custom validation messages for nested fields.

### ISSUE THREAD

**Issue by wujekbogdan** [aldeed/meteor-simple-schema#363]
Data structure:

```javascript
Schemas = {};
Collections = {};

Schemas.Post = new SimpleSchema({
    title: {
        type: String
    },
    category: {
        type: String,
    },
    comments: {
        type: [Object],
        defaultValue: []
    },
    'comments.$.nick': {
        type: String
    },
    'comments.$.content': {
        type: String
    }
});

Schemas.Post.messages({
    'required': 'Generic custom message',
    'required category': 'Specific custom message for category field'
});
```

For top level fields (like **title**) the generic message is displayed. For the **category** field the specific message is displayed. But for the nested fields (like **comments.$.content**) i get the default SimpleSchema message (I mean: **[label] is required**). I tried to override it this way:

``````javascript
Schemas.Post.messages({
   'required comments.$.content': 'My custom, message',
});
```

but it doesn't work.

**// Edit;**

I was able to override default messages for nested fields using global SimpleSchema object.
``````javascript
SimpleSchema.messages({
    required: 'Generic required message'
});
```

But it's a work around not a solution.

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and should fix this bug.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
