### ISSUE TITLE
Schema of Schemas Only Works With Blackbox Enabled

### ISSUE THREAD

**Issue by davidjaenisch** [aldeed/meteor-simple-schema#366]
Hello Aldeed,

I've been working with a schema of schema's. Both the top level schema and subschemas extend a simple "editable" schema. I am working in a Windows environment.

When I don't blackbox the "votes" schema and "comments" schema, comments will be populated but votes will simply be empty {}. The way it chooses the one that works seems to be whichever is called first internally, at least from my perspective.

Gist:
https://gist.github.com/davidjaenisch/add94f5e461d480aa89f

**Comment by mehmedaliosman** [comment]
Yeah, I have this problem too. The problem is that the subschemas aren't being validated when blackboxed. Too bad that nobody answered this.

**Comment by tagrudev** [comment]
Same here

**Comment by aldeed** [comment]
Can someone link to a full reproduction? I'm not sure I totally understand what the issue is. Given the linked schema, what object do you validate to reproduce the issue?

**Comment by tagrudev** [comment]
@aldeed a tree structure like this

```coffeescript
# Sitemap
Schemas.Sitemap = new SimpleSchema(
  tree:
    type: [subSitemap]
    minCount: 1
)
```

here is the schema of the subSitemap

```coffeescript
subSitemap = new SimpleSchema(
  id:
    type: String
    optional: true

  children:
    type: [subSitemap]
    optional: true
    # if the blackbox true is on you can add children but you can't validate the text
    # if it's off you can't add more than one child
    # blackbox: true
)
```

Hope this helps

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
