### ISSUE TITLE
how to pass value into the custom message?

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-simple-schema#375]
I want to pass any values into the custom message
```js
   issueDate: {
        type: String
    },
    expiryDate: {
        type: String
        custom: function () {
            if (this.value < this.field('issueDate').value) {
                // Want to pass this.field('issueDate').value into message below
                return 'expiryDateGt';
            }
        }
    },

// Custom message
SimpleSchema.messages({
    "expiryDateGt": "[label] must be greater then issue date [value].",
});
```

**Comment by ramijarrar** [comment]
Bump

**Comment by thearabbit** [comment]
How to solve?

**Comment by ramijarrar** [comment]
It isn't possible right now as the custom validation functions are only called to get the errorType (see the source [here](https://github.com/aldeed/meteor-simple-schema/blob/master/simple-schema-validation.js#L170))

The reason I bumped this issue was to draw attention to something that I thought would be a useful addition to the package.

**Comment by serkandurusoy** [comment]
Bump!

**Comment by guilhermedecampo** [comment]
This is something needed!! :+1:

**Comment by guilhermedecampo** [comment]
The workaround was:

```
custom: function(){
          var card = new MyAPI.creditCard();
          card.cardCVV = this.value;
          var fieldErrors = card.fieldErrors();
          SimpleSchema.messages({
            "card_cvv": fieldErrors.card_cvv,
          });
          if(fieldErrors.card_cvv) {
            return 'card_cvv';
          }
        }
```

Hope in the future we find a better way!
Cheers,

**Comment by aldeed** [comment]
I'm working on an enhancement to support this

**Comment by guilhermedecampo** [comment]
cool @aldeed !

**Comment by thearabbit** [comment]
Look great!

**Comment by mixcas** [comment]
bump

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
