### ISSUE TITLE
validate() always returns true with constructed custom objects

### ISSUE THREAD

**Issue by cgudrian** [aldeed/meteor-simple-schema#383]
```javascript
var schema = new SimpleSchema({ name: { type: String }});
var context = schema.newContext();

context.validate({}); // correctly returns false
context.validate(new Object()); // correctly returns false

function User() {}
context.validate(new User()); // returns true, should return false
context.validate(new (function() {})); // returns true, should return false
```

**Comment by cgudrian** [comment]
Validation is only performed if ```Utility.isBasicObject``` returns ```true```. Why is this constraint necessary?

**Comment by Matanlb** [comment]
+1

**Comment by aldeed** [comment]
It was mostly because I did not want to continue validating when hitting a Date object, but also there is an assumption that if you have a custom object, you're probably validating it with some custom logic already and possibly storing it into the database using a custom EJSON type.

But there can be an option to whitelist certain types as OK to traverse and validate.

**Comment by Matanlb** [comment]
I think this assumption is quite counter-intuitive, why use scheme validation if the object is passed through custom validation? 
BTW I think a blacklist makes more sense, specifying types that are will pass the validation without traversing, a way saying some objects are validated customly.

**Comment by aldeed** [comment]
I'm referring to custom objects somewhere within the plain object being validated. If the whole object is a custom type, then yes, it would make sense to assume they want to traverse it.

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
