### ISSUE TITLE
Throw a more helpful error when options are misspelled

### ISSUE THREAD

**Issue by AlaaSarhan** [aldeed/meteor-simple-schema#415]
I'd like to suggest renaming 'regEx' for the regular expression rules option to 'regex' since commonly used shorthands for Regular Expression are 'regex' or 'RegExp'. I was writing a schema and I naturally wrote regex instead of regEx and ended up spending half an hour struggling to find why I'm getting "Invalid definition for email field" error.

**Comment by aldeed** [comment]
I'm not sure I want to rename it just because it could cause additional confusion, and supporting both would add complexity. BUT, the error message for misnamed options needs to be made much more clear.

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and should fix this bug.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
