### ISSUE TITLE
defaultValue: [] for array field does not set the value

### ISSUE THREAD

**Issue by gerwinbrunner** [aldeed/meteor-simple-schema#426]
Hi,

I get the following error when I try to insert an object into `TestImages`
```
TestImages.insert({name: "Test Tite 1"})
```
```
Exception while invoking method 'testupDateMethod' Error: Images is required
...
Sanitized and reported to the client as: Images is required [400]
```

Here is the schema:
```
Schemas.TestImages = new SimpleSchema({
  name:
    type: String
  images:
    type: [Object]
    label: 'Images'
    minCount: 0
    defaultValue: []
});
```

How can I make sure that the images array get's initialised with an empty array?

Cheers,
Gerwin

**Comment by chmanie** [comment]
Ran into the same error. The defaultValue can not be set to an empty array. Strings for example work fine (including empty strings).

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and should fix this bug.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
