### ISSUE TITLE
Allow providing custom values for placeholders in messages

### ISSUE THREAD

**Issue by mehmedaliosman** [aldeed/meteor-simple-schema#433]
I have the following situation. I get the text to validate for max length from a wysiwyg editor therefore it's full with html tags. I made a custom validation to to validate the max length where I extract the html and check the length of the raw input. When validation fails I return the string maxString but the problem is that I can't pass the max length integer value to the validation message, the message is displayed like "text cannot exceed [max] characters". I don't wan't to add custom validation message just for this but it seems like I have no  choise.

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.

**Comment by Jofator** [comment]
@aldeed When will be ready SimpleSchema 2.0 stable release?
