### ISSUE TITLE
SimpleSchema.RegEx.Email matches "foo@bar" (without extension)

### ISSUE THREAD

**Issue by jessedvrs** [aldeed/meteor-simple-schema#446]
I suggest using the RFC5322 official standard:

```
(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
```

**Comment by dropfen** [comment]
+
tested with 'SimpleSchema.RegEx.Email.test('foo@bar')'

**Comment by dropfen** [comment]
@jessedvrs I created a pr #450 with the implemented RFC5322 standard from your suggestion, but it fails on `isTrue("name@localhost");` when it comes to testing.

**Comment by aldeed** [comment]
@jessedvrs Where did you find the expression? Is it actually from the spec or someone's interpretation of it?

In reality a valid email is any email that can be resolved, which could include `foo@bar`. This is why the very permissive validation used by most browsers is currently the default. But often depending on the app you might want to be more strict. I am OK with adding an additional `SimpleSchema.RegEx.RFC5322Email` with this if it's an expression that's officially documented or endorsed somewhere. Otherwise I get endless issues asking to tweak the expression for this or that and end up going around in circles.

**Comment by jessedvrs** [comment]
@aldeed Much thanks for your attention. Sorry I didn't mention the source. I believe it was a stack overflow answer with lots of upvotes. But to be honest, I think in the end each regular expression will miss something important and either be too strict or not strict enough, especially for e-mail address validation.

This article points that out http://davidcel.is/posts/stop-validating-email-addresses-with-regex/

An email address regex is a rudimental filter, while in the end you always want to validate whether the user is the owner of the email address and the only way to do that is to use a confirmation email system. For the next minor SimpleSchema version (1.4) I suggest to only check the presence of @. Totally hypocrite to suggest a less strict expression while I opened this issue to make it more strict!

What is your opinion about this?

**Comment by aldeed** [comment]
@jessedvrs I agree; that was basically my point. `SimpleSchema.RegEx.Email` really only validates that there is an `@` with at least one character on each side of it, and that all the characters are allowed for that piece. This seems to be the same as how Chrome and Firefox validate email type fields. So I will just keep that for now, unless anyone can find an expression explicitly mandated by an official spec.

**Comment by jessedvrs** [comment]
Oops, nice! Much thanks pointing this out anyway.
