### ISSUE TITLE
A string is still trimmed for a field that is associated with another schema with trim set to false

### ISSUE THREAD

**Issue by ericching** [aldeed/meteor-simple-schema#452]
```js
Schema.message = new SimpleSchema({
    text: {type: String, max: 255, trim: false, optional: true}
});

Schema.createMessageForm = new SimpleSchema({
    data: {type: Schema.message, optional: false}
});

var form = {
    data: {
        text: "      <--- 4 spaces before and after --->    "
    }
};
Schema.cleanAndValidate('createMessageForm', form);
```

Result: form is now:

```
{
    data: {
        text: "<--- 4 spaces before and after --->"
    }
};
```

**Comment by aldeed** [comment]
What does `Schema.cleanAndValidate` do?

**Comment by ericching** [comment]
Sorry, here it is:

Schema.cleanAndValidate = function (schemaName, objToValidate) {
    var schema = Schema[schemaName];
    if (!schema) {
        logger.error('Cannot clean and validate an unknown schema: ' + schemaName);
        throw new Meteor.Error('invalid-schema', 'The system could not validate the ' + schemaName + ' object. Please contact support at ' + Constants.EMAILS.CONTACT_ADMIN + ' to resolve this.');
    }
    Schema[schemaName].clean(objToValidate);
    var context = Schema[schemaName].namedContext(schemaName + 'Ctx');
    context.validate(objToValidate);
    if (!context.isValid()) {
        var message = schemaName + ': invalid keys - ' + JSON.stringify(context.invalidKeys(), null, 4);
        logger.error(message);
        throw new Meteor.Error('invalid-keys', 'The system could not validate the ' + schemaName + ' object. Please contact support at ' + Constants.EMAILS.CONTACT_ADMIN + ' to resolve this.');
    }
};

**Comment by Siyfion** [comment]
I'm experiencing something very similar to this. I have a schema with field that is set to `trim: false` being referenced in another schema and it simply ignores the `trim` flag and does it regardless! :unamused:

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and should fix this bug.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
