### ISSUE TITLE
Add global options for SimpleSchema.prototype.clean?

### ISSUE THREAD

**Issue by DevinXian** [aldeed/meteor-simple-schema#458]
I'm quite bothered for so many times I must specify validate options  { removeEmptyStrings :false, ...etc} when a document is updated or inserted.
If I can change the global default options for SimpleSchema.prototype.clean?  many thx~
Here is how I fix it temprarily:

    var _clean = SimpleSchema.prototype.clean;

    SimpleSchema.prototype.clean = function (doc, options) {
        _.extend(options, {
            removeEmptyStrings: false
        });//sth. else :)
        _clean.apply(this, [doc, options]);
    };

It seems that  file load order should be cared about, because some document may be inserted when meteor startup

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
