### ISSUE TITLE
What should the type be for moment()?

### ISSUE THREAD

**Issue by JulianKingman** [aldeed/meteor-simple-schema#460]
I can't quite wrap my head around this, what type should I declare for moment() (from moment.js)?
I tried Object, Moment, Date, what's the best way to go about storing a moment object?

**Comment by CaptainN** [comment]
It should be Date, and you should convert your moment object to a date when storing, then convert it back for use when you want to read it.

What would be really nice would be a mutateWrite/mutateRead feature, where you could do that in an attached function on the Schema Definition. I'd like to use that same functionality for converting userId's to an actual user object when the user field is displayed in an autoform, rather than showing the random string of the user's _id.

**Comment by CaptainN** [comment]
BTW, you can handle the mutation on the way in with autoValue. But I'm not sure how to mutate the value on read (or if there is a way).

**Comment by JulianKingman** [comment]
Thanks, that makes sense. So it would be something like new Date(moment())?

**Comment by aldeed** [comment]
- schema should be `type: Date`
- when saving, do `yourMoment.toDate()` and save that
- when retrieving, do `moment(savedValue)` to go back to a moment object
