### ISSUE TITLE
Schema-level custom validator is lost when that schema is merged into another

### ISSUE THREAD

**Issue by medihack** [aldeed/meteor-simple-schema#462]
I attached a custom validator to a sub-schema. Unfortunately it is never called when submitting a form.
But it seems to be supported in the UI of autoform. The sub-schema is shown with afQuickField inside a bootstrap panel (when using autoform-bootstrap). When I attach the validator to the main schema and return an error message then the error message is shown right under the panel header (beside various other places). So it would make sense to attach a validator to a sub-schema and use that panel error field when a sub-schema error occurs.

**Comment by sptessier** [comment]
I have the same issue. It seems like the AutoForm.getFormId() doesn't return a value when used in a sub-schema. I must mention that I'm still runing AutoForm 5.5.1 (meteor 1.1) so I'll try to upgrade and see if it's fixed.

@medihack Did you found a workaround outside of not using a sub-schema?

**Comment by sptessier** [comment]
Same issue with AutoForm 5.7.1 and SimpleSchema 1.3.3 (Meteor 1.2)

**Comment by medihack** [comment]
No, I simply workaround it by adding the validator to the main schema and validate the sub schemas there. It is no big deal, but adding the validator to the sub schema directly would be nicer.

**Comment by yim1990** [comment]
+1

**Comment by aldeed** [comment]
Yeah, currently subschemas are merged into the topmost schema in the constructor and cease to be separate schemas. We could and probably should eventually keep them distinct and cascade down as necessary, but it is a bit of a can of worms. Will keep this open to fix eventually.

**Comment by danielbh** [comment]
Would love to see this fixed. Let me know how I could help.

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
