### ISSUE TITLE
Minimum string length validation does not complain about an empty string

### ISSUE THREAD

**Issue by JcBernack** [aldeed/meteor-simple-schema#486]
I got this in my schema:

    tags: {
        type: [String],
        min: 2,
        max: 32,
        minCount: 1
    }

Trying to insert these values for "tags" yields the following results:
- undefined or null: Tags is required
- empty array []: You must specify at least 1 values
- ["a"]: 0 must be at least 2 characters
- ["ab"]: OK
- ["12345678901234567890123456789012"]: OK
- ["123456789012345678901234567890123"]: Error: 1 cannot exceed 32 characters

So far the validation is working great, but then this happened
- [""]: OK

This is not expected behavior, or is it?
I guess the array-length validation is happy because the array has at least one element and the string length validation is not executed because the string is "null-like".

How can I force the array to contain at least one valid entry?

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and should fix this bug.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
