### ISSUE TITLE
custom validation message on siblingfields

### ISSUE THREAD

**Issue by macroramesh6** [aldeed/meteor-simple-schema#500]
How do send custom validation message to another schema field ?

    SessionSchema = new SimpleSchema({
      'seat.from': {
        type: String,
        max: 10,
        optional: false
      },
      'seat.to': {
        type: String,
        max: 10,
        optional: false
      }
    });
    
    ReservationSchema = new SimpleSchema({
      title: {
        type: String
      },
      sessions: {
        type: [SessionSchema],
        min: 1,
        optional: false,
        custom: function() {
    	 //Its an array object. validation is depends on next array so I made a validation here instead of `SessionSchema`. 
    	 return "greater-session"; // dispaly error on top of the session. I need to display error message on perticular field in `SessionSchema`. 
        }
      }
    });
    
    SimpleSchema.messages({
    	"greater-session": "From seat should not lesser then previous session"
    });

Autoform:

    {{#autoForm id="addReservation" type="method" meteormethod="insertMyReservation" collection="Reservation"}}
     {{> afQuickField name="title" autofocus=''}}
     {{> afQuickField name="sessions" panelClass="group"}}
    {{/autoForm}}

How do I achieve this?

**Comment by dw72** [comment]
+1

**Comment by macroramesh6** [comment]
@dw72 You can try Autoform `before` hook with `AutoForm.addStickyValidationError`.

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
