### ISSUE TITLE
this.unset() does not remove value or property

### ISSUE THREAD

**Issue by j20** [aldeed/meteor-simple-schema#507]
To reproduce, have a property and a value on a document (`query: 'abcd'`), change Simple Schema's autoValue for that property to `this.unset();`, and submit the form. Using `meteor mongo` find the document and note that the property and value still exist on the document.

    query: {
      label: 'Search query',
      type: String,
      optional: true,
      autoValue: function() {
        this.unset();
      }
    },

A workaround for the current time is to return an empty string to clear the value, however that leaves the property itself still defined on the document.

**Comment by aldeed** [comment]
You're misunderstanding what `unset` does. Nothing simple-schema cleaning does has any effect on stored data. You are only manipulating the object while it is being cleaned. So you might be cleaning a document `{query: 'foo', a: 2}`, which your `autoValue` would change to `{a: 2}` because `query` is unset in the object. Or you might be cleaning a modifier `{$set: {query: 'foo', a: 2}}`, which your `autoValue` would change to `{$set: {a: 2}}`.

In your case your intent seems to be to add $unset to the modifier when cleaning it before an update. So you can do that by returning the pseudo-modifier.

```js
autoValue: function () {
  return {$unset: ''};
}
```

Which also implicitly calls `this.unset()`.

**Comment by j20** [comment]
Thanks for the info!
