### ISSUE TITLE
Have a way to pass values to the server in autoValue

### ISSUE THREAD

**Issue by Neobii** [aldeed/meteor-simple-schema#509]
It would be nice if we could use things like Session.get or window.document inside autoValue, but they are not accessible on the server where the actual process runs.

**Comment by aldeed** [comment]
This is more of a collection2 issue (simple-schema has no concept of client vs. server). But it is not possible with collection2 because collection2 uses `deny` functions to achieve what it does, so you only have available what you would have available in a deny function. The only way is to add the necessary information to the doc itself. (Passing options might be possible in the successor to collection2.)
