### ISSUE TITLE
is there a way to build a recursive schema?

### ISSUE THREAD

**Issue by streamnsight** [aldeed/meteor-simple-schema#558]
I have a tree structure with nodes.
nodes have branches (array of nodes) of the same schema.

Can't seem to use the schema name as the type as in [mySchema] within the schema as it comes up with 'not defined' type of error.

i tried using [this] but keys get filtered.

The only way has been using the blackbox function but i'd rather validate all the nodes...

So how should I go about creating a recursive schema like this?

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and will allow you to call `schema.extend()` to do this, although you might run into infinite looping. You can always extend the definition object itself before passing it into the constructor.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
