### ISSUE TITLE
how to attachSchema Meteor.users in ES6 meteor

### ISSUE THREAD

**Issue by aligos** [aldeed/meteor-simple-schema#588]
```
import {Meteor} from 'meteor/meteor';
import {Schema, SimpleSchema, attachSchema} from 'meteor/aldeed:collection2';

export default () => {
  Schema = {};
  Schema.User = new SimpleSchema({
    subscriprions: {
        type: Object
    }
  });
  Meteor.users.attachSchema(Schema.User);
};
```

but error like this
 While processing files with ecmascript (for target os.osx.x86_64):
   server/configs/initial_users.js:5:2: /server/configs/initial_users.js:
   "Schema" is read-only

**Comment by Ethaan** [comment]
You dont need to import `attachSchema ` and `Schema ` from `aldeed:collection2` package.

Take in care that  `Schema = {};` its just a way to make a simple namespace for schemas, by your own, so if you want to to use `Schema = {};`  you should do something like.

`import { App } from '../namespace.js' // or something`

And in order to make `SimpleSchema ` works jus do this.

`import { SimpleSchema } from 'meteor/aldeed:simple-schema';`

**Comment by rubenpa** [comment]
How did you end up getting this working @aligos?

**Comment by aligos** [comment]
i don't use Schema for user anymore. i am creating data to users.profile.yournewdata without adding schema for users.
