### ISSUE TITLE
Getting optional values combining schemas

### ISSUE THREAD

**Issue by Gywem** [aldeed/meteor-simple-schema#600]
I am composing base schemas and then create other from those base ones. I am running into an issue that the base schemas keys are getting the `optional: true` property, they lose the require property and I am not able to change that.

``` javascript
const searchByFieldSchema = new SimpleSchema({
  searchBy: {
    type: [Object],
  },
  'searchBy.$': {
    type: String,
  },
  'searchBy.$.field': {
    type: String,
  }
});

const searchByStringSchema = new SimpleSchema([
  searchByFieldSchema,
  {
  'searchBy.$.value': {
    type: String,
  },
}]);
```

`searchBy` and `searchBy.$` are getting `optional:true`.  Is that an expected behavior?

**Comment by aldeed** [comment]
The extending is intentionally done in that way and is often useful. In SimpleSchema v2, you can pass `requiredByDefault: false` as an option to the constructor, and then it flips so that you do `required: true` in the definitions and otherwise they are optional. Alternatively, I think simply doing `optional: false` in the override in v1 SimpleSchema will work.
