### ISSUE TITLE
Validation for autoValue fields seems not to work

### ISSUE THREAD

**Issue by thorque** [aldeed/meteor-simple-schema#601]
Hello,

I am triying to validate a schema before inserting containing auto value fields:

```javascript
TeamMembers.schema = new SimpleSchema({
    [...]
    createdAt: {
        type: Date,
            denyUpdate: true,
            autoValue: function() {
            if (this.isInsert) {
                return new Date();
            } else if (this.isUpsert) {
                return {$setOnInsert: new Date()};
            } else {
                this.unset();
            }
        }
    },
    [...]
});
TeamMembers.attachSchema(TeamMembers.schema);
const TeamMembersValidationContext = TeamMembers.schema.newContext();
```

In my Meteor method first I am cleaning the document:
```javascript
Meteor.methods({
    'team_member.insert'(team_member){
        TeamMembers.schema.clean(team_member);
        if (TeamMembersValidationContext.validate(team_member)){
            TeamMembers.insert(team_member);
        }else{
            console.log(TeamMembersValidationContext.invalidKeys());
        }
    }
}
```

But the createdAt filed is always invalid. 
```[ { name: 'createdAt', type: 'required', value: null } ]```

What do I wrong?
Thorsten

**Comment by rhettlivingston** [comment]
I stumbled on this while browsing for something else and believe I know your answer though I'm no expert.

You're confusing the functionality of collection2 with SimpleSchema. The "this.isInsert" and "this.isUpsert" references within your autovalue function are only provided by collection2. See https://github.com/aldeed/meteor-collection2#autovalue. 

You could solve your problem by providing "isInsert: true" to clean using extendAutoValueContext just like collection2 does (actually collection2-base if you go looking for the code).

If you're using collection2 though, all of this should be getting done for you in the TeamMembers.insert. Calling clean and validate yourself shouldn't be necessary. Since you attached the schema to TeamMembers, it appears to me that your code is attempting to duplicate what is happening in TeamMembers.insert anyway.

**Comment by rhettlivingston** [comment]
Just a note for any maintainer of meteor-simple-schema that looks at this... the README points to the examples in collection2's README. I quickly eyeballed them and only see one autovalue specification among them that I believe would work without collection2. Sure, the text just above them points out that collection2 is extending the context, but users coming from here are looking straight to the examples. It might be good to have examples here that don't require collection2 functionality.

**Comment by thorque** [comment]
@rhettlivingston thanks for clarification. I've removed the additional validation.
