### ISSUE TITLE
Having trouble with custom field validation

### ISSUE THREAD

**Issue by jkd65** [aldeed/meteor-simple-schema#630]
![image](https://cloud.githubusercontent.com/assets/10778294/16529379/62c11a0a-3f77-11e6-957e-843c54d9fe80.png)

It gets all the way to the result if statement and console.logs "results matched" but fails to return the validation and throw an error on the form.

Appreciate any help!

**Comment by d4nyll** [comment]
The Meteor method call is done asynchronously, and so the `custom` function is completed (with nothing returned) before the callback you provided is ran. Since nothing was returned, the schema assumes the validation passed.

**Comment by d4nyll** [comment]
A Meteor method call is done asynchronously. So the `custom` function is completed (with nothing returned) before the callback you defined is ran. Since nothing was returned, the schema assumes validation passed.

See https://github.com/aldeed/meteor-simple-schema#asynchronous-custom-validation-on-the-client on how you may deal with this issue.

**Comment by jkd65** [comment]
Thank you!

**Comment by thearabbit** [comment]
But I have problem with `onSuccess hook`, it always run although get error.
```js
onSuccess (formType, result) {
        console.log('result', result);
    },
```
