### ISSUE TITLE
Define that only one object in collection should have it (choose)

### ISSUE THREAD

**Issue by piotrekfracek** [aldeed/meteor-simple-schema#632]
Sorry for poor title, here is better explanation of my question:
I have collection called Languages. I'd like to allow to choose default language. Is there any possibility to define in schema, that only one language can have isDefault = true?

**Comment by aldeed** [comment]
No this wouldn't be possible since you'd have to do database queries to check. SimpleSchema doesn't know anything about databases, so it couldn't be in this package. Maybe there would be some way to add it to collection2 package, but I think the only foolproof way would be if MongoDB allows you to define this, similar to a unique index.
