### ISSUE TITLE
Unmaintained

### ISSUE THREAD

**Issue by gooor** [aldeed/meteor-simple-schema#640]
It looks like this repo is unmaintained, I would suggest not to use it on production. I have more problems with it than it solves (empty strings, untrackable errors, etc)

**Comment by ElegantSudo** [comment]
@gooor what would you recommend?

**Comment by Taakn** [comment]
@aldeed first of all thank you so much for your fantastic work on Simple Schema. As others have noted, it doesn't look like you maintain this repo anymore. What are your plans on the long term with this? What are the risks that it stop working with new meteor releases?

Thanks

**Comment by Taakn** [comment]
@ElegantSudo @gooor MongoDB is now offering document validation (https://docs.mongodb.com/manual/release-notes/3.2/#document-validation)

SimpleSchema+Collection2 seem to have a lot more features, but using document validation seems to make sense to me.

**Comment by ElegantSudo** [comment]
@Taakn thanks, this is really great!

**Comment by JeremyIglehart** [comment]
Does anybody have any experience using https://github.com/jagi/meteor-astronomy/ and could comment about it?

**Comment by JeremyIglehart** [comment]
@Taakn, do you have any experience using the validator option in conjunction with meteor?

**Comment by jhuenges** [comment]
@JeremyIglehart using it in a new project and I am very happy with it. And on top of that, the maintainer answers to questions within 24 hours

**Comment by JeremyIglehart** [comment]
Thanks @jhuenges - I appreciate the input.  It seams to me that [MDG is showing interest](https://github.com/meteor/guide/issues/53) in helping simple-schema keep up to speed and I think it's worth mentioning in this thread.

I'm confused why it's been so long and no one has responded to this thread.

**Comment by aldeed** [comment]
SimpleSchema 2.0 is basically done. I'm just going through and trying to make sure everything is documented because a lot has changed. All outstanding bugs are fixed in 2.0, so I'll be going through and closing those once I have the release candidate published.

It is up to you whether you want to migrate to 2.0 or to some other solution. Both will require a little rewriting. I haven't decided yet whether I'll port any of the bug fixes back to 1.x. Kinda depends on how much time I have.

**Comment by aldeed** [comment]
btw, 2.0 in progress is over here: https://github.com/aldeed/node-simple-schema

I will be publishing this Meteor package, too, which will just wrap the node package and inject the reactivity.

**Comment by JeremyIglehart** [comment]
@aldeed Eric, AMAZING!  Thank's so much for your hard work and dedication.  You're really an inspiration to all of us.  I spent a few hours looking around, and Simple-Schema really is the goto thing.  You've saved many of us all from a lot of hard work.  So, I just want to be first in line to say THANKS!

**Comment by aldeed** [comment]
Thanks @JeremyIglehart

**Comment by JeremyIglehart** [comment]
@aldeed - Eric, I have a few questions about Version 2.0 if you don't mind.

1. When do you think the 2.0 version will be ready to work in Meteor? I'm excited to give it a try and get it into a project I'm working on right now to test it out.
2. Will it work out-of-the-box with things like collection2 and autoform?

Thanks again for all your hard work! :)

**Comment by aldeed** [comment]
@JeremyIglehart You should be able to try now by npm installing it by commit hash if you are daring, but hopefully I will get it fully documented and published on npm within the next week. Collection2 will need one small change, which I will try to do asap. Autoform will need changes, too, but I haven't done any testing with autoform yet. I think the changes to those two packages will be relatively straightforward and backward compatible.

**Comment by aldeed** [comment]
I have tried to keep track of most of the big changes here, though not all of these are properly documented yet: https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200

**Comment by JeremyIglehart** [comment]
@aldeed Wow, that sure is a lot of work.  You're a hero Eric.  Thanks so much for responding, and thank you again for all the hard work you do!

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.

**Comment by JeremyIglehart** [comment]
@aldeed - I'm confused a bit.  I'm working on an app that will shortly be running in a production mode.  Today I am adding in Simple Schema (Because there really is no other way as far as I can tell to write "Advanced Meteor Methods" without using it for the validation method).  But I"m stuck trying to decide between [meteor-simple-schema](https://github.com/aldeed/meteor-simple-schema) and [node-simple-schema](https://github.com/aldeed/node-simple-schema/).  Would I be correct in assuming that [meteor-simple-schema](https://github.com/aldeed/meteor-simple-schema) is on the way out and [node-simple-schema](https://github.com/aldeed/node-simple-schema/) is on the way in?

Does that mean I should use [node-simple-schema](https://github.com/aldeed/node-simple-schema/) now?  Or not...?

**Comment by aldeed** [comment]
@JeremyIglehart In order to use for method validation, you have to either use the Meteor package or implement the same `Meteor.Error` override that I have in that package. I want to work with MDG to update the DDP package to pass any errors back to the client if they've been "marked" as client safe, but until that happens it has to throw a `ValidationError` (which is actually a special `Meteor.Error`) which of course the NPM package does not do by default because it can't depend on Meteor packages.

https://github.com/aldeed/meteor-simple-schema/blob/devel/main.js#L4-L21

Incidentally, "advanced Meteor methods" only require that you throw a `ValidationError` when arguments are invalid, so you could use or write anything to do that. Doesn't have to be SimpleSchema. That error type comes from the `mdg:validation-error` Meteor package.

**Comment by JeremyIglehart** [comment]
@aldeed Thanks so much!  For now, I might implement check/match until I wait for SimpleSchema 2.0 to stabilize.  If I end up doing something custom, I'll report back for interest sake.

Thanks for your advice and all of your hard work - you're one of my "developer role models".

**Comment by smartdemocracy** [comment]
https://www.npmjs.com/package/simpl-schema
