### ISSUE TITLE
clean does not convert 'true' to true or 'false' to false for booleans

### ISSUE THREAD

**Issue by davidjcastner** [aldeed/meteor-simple-schema#645]
Not sure if this was intended, but when cleaning a boolean field with a string of `'true'` or `'false'` , it does not convert it accordingly.

Example:

``` js
const schema =  new SimpleSchema({ test: { type: Boolean }});

let dataTrue = { test: 'true' };
schema.clean(dataTrue);
console.log(dataTrue); // { test: 'true' }
schema.validate(dataTrue); // throws error

let dataFalse = { test: 'false' };
schema.clean(dataFalse);
console.log(dataFalse); // { test: 'false' }
schema.validate(dataFalse); // throws error
```

> Note only has a minor use case
> 
> Reason for converting `'true'` to `true` / Use case:
> 
> If data is attached to the html using the data attribute, it will only accept a string. When parsing it later it would be convenient to have clean convert it properly.

I understand if it does not convert 'false' to false because `Boolean('false') === true`, but converting either non empty strings to true or at least 'true' to true would make sense in my opinion; however, if this is intentional that's okay I already have a workaround.

**Comment by ro6** [comment]
I actually started to write a patch for this, but realized that converting from String to Boolean is tricky because there isn't one obviously right way to do it, so you'd end up picking an arbitrary mapping if you only had one implementation inside SimpleSchema. For now you can either do the conversion before passing in to SimpleSchema, or use autoValue on a per-field basis to do type conversion. 

An interesting and powerful way to solve this issue and similar ones in the future would be for SimpleSchema to provide a pluggable type conversion system. The user could provide an function at the global (all SimpleSchemas within my project), schema instance, or field level (more specific overriding for the same conversion type) for converting to the target field 'type'. SimpleSchema could ship with some sensible options for common type conversions like String -> Boolean and you could choose the ones you want to use at the scope you want them to apply, sort of the way error message overriding works now.

The system could use one function for each target value (ie Any -> Boolean, Any -> Number) or one function for each pair (ie String -> Boolean, String -> Number, Number -> Boolean). 

@aldeed Any sense of whether a more general solution like this would be widely useful? Does the problem come up often enough to justify the extra work?

**Comment by aldeed** [comment]
@ro6, yeah, cleaner plugins is something that has been on the nice-to-have list for some time. I didn't get it into v2, but hopefully eventually. If it's something you want to work on, let me know.

As for the original request, I think I'd be OK with having the exact strings `"true"` and `"false"` converted to their boolean values and with having the Numbers 1 and 0 converted to `true` and `false` respectively since those are pretty obvious and common conventions. If someone wants to add it, the code in v2 is here: https://github.com/aldeed/node-simple-schema/blob/master/lib/clean/convertToProperType.js

**Comment by aldeed** [comment]
Created an issue for this in the NPM repo
