### ISSUE TITLE
[V2] Remove Npm dependency on simpl-schema

### ISSUE THREAD

**Issue by clayne11** [aldeed/meteor-simple-schema#663]
The end user should have to install the package from `npm`. By setting the dependency in the `package.js` file you're locking the version down to the one in the Meteor package and you also end up with a duplicate of the package.

I personally use `simpl-schema` for form validation as well as for my Meteor collection validation and my front-end is built with Webpack not Meteor so I can't have any dependencies on Meteor packages.

Letting the developer bring their own version of `simpl-schema` is much more flexible.

**Comment by yanickrochon** [comment]
Especially since i just replaced the npm package with this one, because I installed Collection2, and now my schemas fail because of various issues. I have checked and the version seems to match, but it is definitely *not* the same package.

**Comment by aldeed** [comment]
I don't think this is necessary anymore since I'm now suggesting you use the NPM package directly. We need to get all package authors to make new versions that have peer dependencies on the npm pkg, like I've done with collection2. See https://github.com/aldeed/meteor-collection2#important-note-the-version-in-this-repo-is-deprecated
